In [2]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [4]:
np.zeros([3,3])


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.random.rand(3,4)

array([[0.37043051, 0.02150667, 0.24357075, 0.9638261 ],
       [0.3712697 , 0.5075697 , 0.96878361, 0.59447729],
       [0.00968949, 0.36574472, 0.63079534, 0.40968277]])

In [8]:
ar1=np.array([[1,2,3],[10,20,30]])
ar2=np.array([5,5,5])
ar1+ar2

array([[ 6,  7,  8],
       [15, 25, 35]])

In [9]:
nums=np.array([12,19,20])
np.square(nums)

array([144, 361, 400])

In [10]:
np.exp(nums)

array([1.62754791e+05, 1.78482301e+08, 4.85165195e+08])

In [11]:
np.sin(nums)

array([-0.53657292,  0.14987721,  0.91294525])

In [12]:
np.max(nums)

20

In [13]:
np.sum(nums)

51

In [16]:
np.shape(nums)

(3,)

In [17]:
np.average(nums)

17.0

In [18]:
np.mean(nums)

17.0

In [19]:
np.median(nums)


19.0

In [21]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[1:2,2:]

array([[6]])